run-name: ${{github.actor}} is deploying

name: deploy_frontend

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: to_do_frontend
    outputs:
      artifact_name: ${{steps.artifact_name.outputs.artifact_name}}
    steps:
      - uses: actions/checkout@v3

      - run: echo deployment started

      - run: |
          npm install
      - run: npm run build
      - run: |
          cd build
          ls -lrta

      - run: echo deployed
      - run: echo "artifact_name=${{github.event_name}}-artifact" >> $GITHUB_OUTPUT
        id: artifact_name
      - uses: actions/upload-artifact@v4
        with:
          path: to_do_frontend/build
          name: ${{github.event_name}}-artifact
          overwrite: true

  download-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        env:
          artifact_name: ${{needs.build.outputs.artifact_name}}
        with:
          name: ${{needs.build.outputs.artifact_name}}
      - run: ls -lrta
