run-name: ${{github.actor}} is deploying

name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: to_do_frontend

    steps:
      - uses: actions/checkout@v3

      - run: echo deployment started

      - run: |
          npm install
      - run: npm run build
      - run: |
          cd build
          ls -lrta

      - run: echo deployed

      - uses: actions/upload-artifact@v4
        with:
          path: to_do_frontend/build
          name: ${{github.event_name}}-artifact
          overwrite: true
