run-name: ${{github.actor}} is deploying

name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: to_do_frontend
    
    steps:
        - run: echo deployment started
        - uses: actions/checkout@v3

        - run: |
            npm install
        - run: npm run build

        - run: |
            cd build
            ls -lrta

        - run: echo deployed
