run-name: ${{github.actor}} is deploying

name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: to_do_frontend
    
    steps:
        - uses: actions/checkout@v3

        - run: |
            npm install
        - run: npm build

        - working-directory: build
          run: tree

        - run: echo end
