name: issue_details

on: 
    issues: 
        types: 
            - opened
jobs:
    issue_info:
        runs-on: ubuntu-latest
        steps:
            - name: issue_info
              run: echo ${{github.env.issue}}