name: issue_details
on:
  issues:
    types:
      - opened
      - closed
      - reopened
  pull_request:
    types:
      - opened
    branches: main

jobs:
  issue_info:
    runs-on: ubuntu-latest
    # if: github.event.issue.state == 'closed'
    if: endsWith(github.actor,'chand')
    steps:
      - name: issue_info
        run: echo "${{toJson(github.event.issue)}}"
