name: reusable workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: "name of the actor"
    outputs:
      status:
        value: ${{jobs.build.outputs.step_result}}
        description: "job result"
    secrets:
      password:
        required: true
        description: "I need your password buddy"

jobs:
  build:
    if: true
    defaults:
      run:
        working-directory: "to_do_frontend/"
    outputs:
      step_result: ${{steps.output.outputs.step_result}}
    strategy:
      matrix:
        node-version:
          - 18
        os:
          - ubuntu-latest
          - windows-latest
        exclude:
          - os: windows-latest

    runs-on: ${{matrix.os}}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        id: get_code
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Echo name
        run: echo "${{inputs.name}}"
      - name: Print secrets
        run: echo "${{secrets.password}}"

      - name: outputs
        run: echo "step_result=success" >> $GITHUB_OUTPUT
        id: output
