name: Test React

on:
    push:
        branches:
            - main
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:

            - name: start
              env:
                  NAME: Chand Basha
              run: echo started by ${NAME}
            - name: install
              run: npm install
            - name: run
              run: npm start
              