name: Test React

on:
    push:
        branches:
            - main
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./to_do_frontend
        steps:
            -   uses: actions/checkout@v3
                name: get code

            -   name: setup nodejs
                uses: actions/setup-node@v4
                with:
                    node-version: '18'
            -   name: install
                run: npm install

            -   name: build
                run: npm run build
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        # needs: test
        defaults:
            run:
                working-directory: ./to_do_frontend
        steps:
            -   uses: actions/checkout@v3
                name: get code

            -   name: setup nodejs
                uses: actions/setup-node@v4
                with:
                    node-version: '18'
            -   name: install
                run: npm install

            -   name: build
                run: npm run build
            
            -   name: Deploying
                run: echo "Deploying"