name: Test React

on:
    push:
        branches:
            - main
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:

            - name: start
              env:
                  NAME: Chand Basha
              run: echo started by ${NAME}
            - uses: actions/checkout@v3
            - name: go_to_react_folder
              run: cd to_do_frontend/&&ls -lrta
            - name: install
              run: npm install
            - name: run
              run: npm start
              