name: using reusable workflow

on: push

jobs:
  matrix:
    uses: "./.github/workflows/reusable.yml"

    with:
      name: ${{github.actor_id}}
    secrets:
      password: don is ${{github.actor}}

  print_matrix_outputs:
    needs: matrix
    runs-on: ubuntu-latest
    steps:
      - name: print_matrix_outputs
        run: echo "${{needs.matrix.outputs.status}}"
